<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboparty_dexhand</name>
  <version>0.4.2</version>
  <description>RP_Hand dexterous hand driver for Linux CAN-FD with C++ and Python factory APIs</description>
  <maintainer email="ZhihaoLiu_hit@163.com">Roboparty</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>fmt</depend>
  <depend>spdlog</depend>
  <build_depend>pybind11_vendor</build_depend>
  <build_depend>python3-dev</build_depend>
  <exec_depend>python3</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
